In [37]:
pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\kansa\anaconda3\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pandas as pd
import psycopg2 #library to connect to postgresSQL using connection string
from sqlalchemy import create_engine

In [39]:
order_df = pd.read_csv("../datasets/orders.csv")

In [40]:
order_df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [41]:
aisles_df = pd.read_csv("../datasets/aisles.csv")
departments_df = pd.read_csv("../datasets/departments.csv")
order_products_df = pd.read_csv("../datasets/order_products__prior.csv").sample(10000)
products_df = pd.read_csv("../datasets/products.csv")

In [42]:
aisles_df.head()
departments_df.head()
order_products_df.head()
products_df.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [100]:
try:
    conn = psycopg2.connect(dbname = 'kartik_test_db',user = 'postgres',password = 'root',port = 5432)#for writing create table queries directly here
except:
    print('Connection unsuccessful')

In [101]:
cur = conn.cursor()

In [102]:
engine = create_engine('postgresql+psycopg2://postgres:root@localhost/kartik_test_db') #to insert the dataframes (made by cvs datasets and pandas) directly to db

In [103]:
cur.execute("""
CREATE TABLE aisles (
    aisle_id INTEGER PRIMARY KEY,
    aisle VARCHAR
)
""")

In [104]:
cur.execute("""
CREATE TABLE departments (
    department_id INTEGER PRIMARY KEY,
    department VARCHAR(255)
)
""")

In [105]:
#conn.rollback()

In [106]:
cur.execute("""
CREATE TABLE products (
    product_id INTEGER PRIMARY KEY,
    product_name VARCHAR(255),
    aisle_id INTEGER,
    department_id INTEGER,
    FOREIGN KEY (aisle_id) REFERENCES aisles (aisle_id),
    FOREIGN KEY (department_id) REFERENCES departments (department_id)
)
""")

In [107]:
cur.execute("""
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    order_number INTEGER,
    order_dow INTEGER,
    order_hour_of_day INTEGER,
    days_since_prior_order INTEGER )
""")

In [108]:
cur.execute("""
CREATE TABLE order_products (
    order_id INTEGER,
    product_id INTEGER,
    add_to_cart_order INTEGER,
    reordered INTEGER,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES orders (order_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id)
    )
""")

In [109]:
conn.commit()

In [72]:
order_df.drop('eval_set', inplace=True, axis=1)

KeyError: "['eval_set'] not found in axis"

In [74]:
order_df.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [110]:
aisles_df.to_sql('aisles', con = engine,if_exists = 'append', index = False)

134

In [115]:
departments_df.to_sql('departments', con=engine, if_exists='replace', index=False)

InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table departments because other objects depend on it
DETAIL:  constraint products_department_id_fkey on table products depends on table departments
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL:
DROP TABLE departments]
(Background on this error at: https://sqlalche.me/e/14/2j85)

In [116]:
products_df.to_sql('products', con=engine, if_exists='append', index=False)

688

In [118]:
order_df.to_sql('orders', con=engine, if_exists='append', index=False)

83

In [119]:
order_products_df.to_sql('order_products', con=engine, if_exists='append', index=False)

1000